### ISSUE TITLE
What can I do with it?

### ISSUE THREAD

**Issue by reinzor** [piappl/robotic-map#2]
For the R5COP project, we would like to use your software on our robotics platform AMIGO (http://www.techunited.nl/nl/amigo). Could you maybe provide tutorials or a description how to use it for other platforms and what the functionality is? Maybe via Skype?

**Comment by adamdbrw** [comment]
All right!

Have you read the documentation on how to use the map interface? See the docs folder.

Have you tried running the binaries? 
With the map library comes the rosmapinterface, which is a ROS package (you can build it inside your ROS workspace if you wish) that supplies a simple ROS node wrapper for the map as an example of how to use it. So, try out the binaries first:
- run rosmapinterface
- run fakerobot

The (fake) robot should display on the map, indicating that all is properly installed.

From there on, you can start with using the rosmapinterface node or go to integrating the map library directly with your existing ROS package, using rosmapinterface as a guideline.

The first case is the easiest. Just take a look at ROS messages that come with the wrapper (for R5-Cop, they are described also in WP24 deliverables). Two messages are provided in the example:
- RobotInformation.msg : your robot has to publish this on /robot_introduction topic in order to appear on the map. (See fake robot, it does exactly that).
- WaypointInformation.msg : through the map interface, you can indicate where you want your robot to go.

You can add a local map (see map/localmap directory, it is deployed during installation, just switch the files with your own map where Amigo is).

You can also add a proper icon for your robot, just give it the same name as your robot sends in RobotInformation.msg (map/icons/defaultRobot.png is used by default if no icon <yourrobotname>.png is found.

**Comment by adamdbrw** [comment]
If you need the interface extended/would like some functionality for the map that would be useful to you:
- Ask me to implement it
- .. or implement it yourself (I will help) -> this could look good on review report.

**Comment by reinzor** [comment]
Thanks for your info, I missed the PDF in the doc directory. Together with Jesse, I was looking for a way to integrate your work in the indoor robot cleaning demonstrator. 

However, for us it is not clear what value your work would add to our demonstrator. Especially since it is indoor, on a small scale and the relation between global and local is not really important for our use case.

**Comment by adamdbrw** [comment]
Yeah, on that you will have to decide yourself. Think of the value that the map interface could have (possibly through some new functionality, which I can make happen).
